#!/usr/bin/env bash
# 01-configure-apt
#
# Configuramos los Sources
#
echo -e "\033[32;40;7m Configruacion de los nuevos respositorios \033[0m"
sleep 2
rm /etc/apt/sources.list
rm /etc/apt/sources.list.d/*
if [ -z "$REPO" ]; then
    $REPO = 'mirror://mirrors.ubuntu.com/mirrors.txt'
fi
echo "deb $REPO trusty main universe multiverse" >> /etc/apt/sources.list
echo "deb $REPO trusty-updates main universe multiverse" >> /etc/apt/sources.list
echo "deb $REPO trusty-backports main restricted universe multiverse" >> /etc/apt/sources.list
echo "deb http://security.ubuntu.com/ubuntu trusty-security main universe multiverse" >> /etc/apt/sources.list
echo "deb http://archive.canonical.com/ubuntu trusty partner" >> /etc/apt/sources.list
aptitude update
#aptitude -y full-upgrade
