#!/usr/bin/env bash
# 01-configure-apt
#
# Configuracion de HostName
#
echo -e "\033[32;40;7m Setting Timezone & Locale to UTC & C.UTF-8 \033[0m"
sleep 2
echo 'LANGUAGE="en_US.UTF-8"' >> /etc/default/locale
echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale > /dev/null 2>&1
echo "LANG=en_US.UTF-8" >> /etc/default/locale > /dev/null 2>&1
echo "LC_ALL=en_US.UTF-8" >> /etc/default/locale > /dev/null 2>&1
locale-gen en_US.UTF-8 > /dev/null 2>&1
dpkg-reconfigure locales > /dev/null 2>&1
ln -sf /usr/share/zoneinfo/UTC /etc/localtime

aptitude update
aptitude install -y curl unzip git-core ack-grep software-properties-common \
build-essential dbus nano aptitude supervisor
aptitude install -y locales
aptitude install -y util-linux-locales

aptitude install -y ntp ntpdate
service apparmor stop
update-rc.d -f apparmor remove
aptitude -y remove apparmor apparmor-utils
sudo useradd -g www-data vagrant
sudo useradd -g www-data root

# Definimos que las actualizaciones de seguridad puedan instalarse automaticamente
aptitude install -y unattended-upgrades
echo "APT::Periodic::Unattended-Upgrade \"1\";" >> /etc/apt/apt.conf.d/10periodic
