#!/usr/bin/env bash
echo -e "\033[32;40;7m Instalacion de NewRelic\033[0m"
echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
aptitude update
aptitude install -y newrelic-sysmond
nrsysmond-config --set license_key=$NR_LICENCE
/etc/init.d/newrelic-sysmond start
php -v > /dev/null 2>&1
PHP_IS_INSTALLED=$?

nginx -v > /dev/null 2>&1
NGINX_IS_INSTALLED=$?

function php_agent() {
aptitude install -y newrelic-php5
newrelic-install install
echo "Licencia"
sed -i "s/newrelic_license_key=YOUR_LICENSE_KEY_HERE/newrelic_license_key=$NR_LICENCE/" /etc/php5/fpm/conf.d/newrelic.ini
echo "App name"
sed -i "s/newrelic.appname = \"PHP Application\"/newrelic.appname = \"$HOSTNAME\"/" /etc/php5/fpm/conf.d/newrelic.ini
service php5-fpm restart
}

function newrelic_agent() {
aptitude install -y nginx-nr-agent
sed -i "s/newrelic_license_key=YOUR_LICENSE_KEY_HERE/newrelic_license_key=$NR_LICENCE/" /etc/nginx-nr-agent/nginx-nr-agent.ini
service nginx restart
}



if [[ $PHP_IS_INSTALLED -eq 0 ]]; then
    while true; do
        read -p "¿Desea instalar PHP Agent?: " yn
        case $yn in
            [Yy]* ) php_agent; break;;
            [Nn]* ) exit;;
            * ) echo "Seleccione una opcion valida.";;
        esac
    done
fi

if [ $NGINX_IS_INSTALLED -eq 0 ]; then
    while true; do
        read -p "¿Desea instalar Nginx Agent?: " yn
        case $yn in
            [Yy]* ) newrelic_agent; break;;
            [Nn]* ) exit;;
            * ) echo "Seleccione una opcion valida.";;
        esac
    done
fi
