#!/usr/bin/env bash
echo -e "\033[32;40;7m Instalacion de NewRelic\033[0m"
LICENCE=
echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
aptitude update
aptitude install -y newrelic-sysmond
nrsysmond-config --set license_key=$LICENCE
/etc/init.d/newrelic-sysmond start
