#!/usr/bin/env bash
echo -e "\033[32;40;7m Instalacion Loggy\033[0m"
sleep 2

if [ -n "$PGSQL_PASS" ]  || [ -n "$PGSQL_PASS" ] || [ -n "$PGSQL_PASS" ]; then
    curl -O https://www.loggly.com/install/configure-linux.sh
    sudo bash configure-linux.sh -a $LOGGLY_ACCOUNT -t $LOGGLY_KEY -u $LOGGLY_USER
    nginx -v > /dev/null 2>&1
    NGINX_IS_INSTALLED=$?
    if [ $NGINX_IS_INSTALLED -eq 0 ]; then
        curl -O https://www.loggly.com/install/configure-nginx.sh
        sudo bash configure-nginx.sh -a $LOGGLY_ACCOUNT -t $LOGGLY_KEY -u $LOGGLY_USER
    fi
fi
