#!/usr/bin/env bash
echo -e "\033[32;40;7m Instalacion Lynis\033[0m"
sleep 2
curl https://cisofy.com/files/lynis-2.1.1.tar.gz -o lynis.tar.gz
tar xvfz lynis.tar.gz -C /opt/
rm lynis.tar.gz
DIR=${pwd}
cd /opt/lynis/
./lynis -c -Q
cd $DIR
