#!/usr/bin/env bash
# Limpiamos la instalacion anterior

aptitude purge -y nginx*
rm -rf /etc/nginx/
rm -rf /var/www/

echo "\033[32;40;7m Instalacion Nginx\033[0m"
sleep 2
add-apt-repository -y ppa:nginx/stable
aptitude update
aptitude install -y nginx
sed -i "s/user www-data;/user $USER;/" /etc/nginx/nginx.conf
sed -i "s/# server_names_hash_bucket_size.*/server_names_hash_bucket_size 64;/" /etc/nginx/nginx.conf
touch /var/log/nginx/access.log
touch /var/log/nginx/error.log

cat <<EOF >/etc/nginx/sites-available/default
server {
	listen 80;
	root /var/www;
	index index.html index.php;
	server_name _;
	access_log /var/log/nginx/access.log;
	error_log  /var/log/nginx/error.log error;
	charset utf-8;

	location / {
		try_files \$uri \$uri/ /app.php?\$query_string /index.php?\$query_string;
	}

	location = /favicon.ico { log_not_found off; access_log off; }
	location = /robots.txt  { log_not_found off; access_log off; }

	error_page 404 /index.php;

	location ~ \.php$ {
		try_files \$uri =404;
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		# With php5-fpm:
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
		fastcgi_param LARA_ENV local;
		fastcgi_param HTTPS off;
	}
	# Deny .htaccess file access
	location ~ /\.ht {
		deny all;
	}
}
EOF


cat <<EOF >/var/www/index.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap 101 Template</title>
    <link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.4/css/bootstrap.css.map" rel="stylesheet">
  </head>
  <body>
    <?php phpinfo() ?>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  </body>
</html>
EOF

usermod -a -G www-data $USER
rm -rf /var/www/html/
chmod -R 755 /var/www
