#!/usr/bin/env bash
# Limpiamos la instalacion anterior
aptitude purge -y nginx*
rm -rf /etc/nginx/
rm -rf /var/www/
# Limpiamos la instalacion anterior

echo "\033[32;40;7m Instalacion Nginx\033[0m"
sleep 2
wget http://nginx.org/keys/nginx_signing.key
apt-key add nginx_signing.key
echo "deb http://nginx.org/packages/ubuntu/ trusty nginx" >> /etc/apt/sources.list.d/nginx.list
aptitude update
aptitude install nginx
